In [122]:
%matplotlib inline
import numpy as np
import pandas as pd

In [123]:
index = pd.date_range('01/01/2020','12/31/2020',periods=8)
index

DatetimeIndex([          '2020-01-01 00:00:00',
               '2020-02-22 03:25:42.857142857',
               '2020-04-14 06:51:25.714285714',
               '2020-06-05 10:17:08.571428572',
               '2020-07-27 13:42:51.428571428',
               '2020-09-17 17:08:34.285714284',
               '2020-11-08 20:34:17.142857144',
                         '2020-12-31 00:00:00'],
              dtype='datetime64[ns]', freq=None)

In [124]:
df = pd.DataFrame(np.random.randn(8,3),index = index, columns=["A",'B','C'])
df

A         B         C
2020-01-01 00:00:00.000000000 -0.779702 -0.843896 -0.150534
2020-02-22 03:25:42.857142857 -0.965558  0.150489 -0.113421
2020-04-14 06:51:25.714285714  2.633528 -1.025091 -0.782048
2020-06-05 10:17:08.571428572  0.423943  0.872705  2.287226
2020-07-27 13:42:51.428571428  1.622920  0.823733  0.293059
2020-09-17 17:08:34.285714284  0.896630 -0.610322 -0.316166
2020-11-08 20:34:17.142857144 -1.482424 -0.228848  0.962641
2020-12-31 00:00:00.000000000 -0.209692 -0.774043 -0.359778

In [125]:
df.columns = [x.lower() for x in df.columns]
df

a         b         c
2020-01-01 00:00:00.000000000 -0.779702 -0.843896 -0.150534
2020-02-22 03:25:42.857142857 -0.965558  0.150489 -0.113421
2020-04-14 06:51:25.714285714  2.633528 -1.025091 -0.782048
2020-06-05 10:17:08.571428572  0.423943  0.872705  2.287226
2020-07-27 13:42:51.428571428  1.622920  0.823733  0.293059
2020-09-17 17:08:34.285714284  0.896630 -0.610322 -0.316166
2020-11-08 20:34:17.142857144 -1.482424 -0.228848  0.962641
2020-12-31 00:00:00.000000000 -0.209692 -0.774043 -0.359778

In [126]:
np.random.seed(42)
s = pd.Series(np.random.randn(5), index=["a","b","c","d","e"])
np.array(s) , s.to_numpy()

(array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337]),
 array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337]))

In [127]:
s.array, s.index.array

(<PandasArray>
 [  0.4967141530112327, -0.13826430117118466,   0.6476885381006925,
    1.5230298564080254, -0.23415337472333597]
 Length: 5, dtype: float64,
 <PandasArray>
 ['a', 'b', 'c', 'd', 'e']
 Length: 5, dtype: object)

In [128]:
df.to_numpy()

array([[-0.77970188, -0.84389636, -0.15053386],
       [-0.96555767,  0.15048908, -0.11342125],
       [ 2.63352822, -1.02509089, -0.78204783],
       [ 0.42394307,  0.8727051 ,  2.28722598],
       [ 1.6229205 ,  0.82373308,  0.29305925],
       [ 0.89663038, -0.61032202, -0.3161659 ],
       [-1.48242425, -0.22884752,  0.96264129],
       [-0.20969244, -0.77404293, -0.35977815]])

In [129]:
df = pd.DataFrame(
                    {
                        "one" : pd.Series(np.random.randint(100, size=3) ,index=["a","b","c"] ),
                        "two" : pd.Series(np.random.randint(100, size=4),index=["a","b","c","d"]),
                        "three" : pd.Series(np.random.randint(100, size=3),index=["b","c","d"])
                    }
                 )
df

one  two  three
a  74.0   99    NaN
b  74.0   23   52.0
c  87.0    2    1.0
d   NaN   21   87.0

In [130]:
row = df.iloc[1]
col = df['two']
row


one      74.0
two      23.0
three    52.0
Name: b, dtype: float64

In [131]:
df.sum(axis=0), df.sum(axis=1)

(one      235.0
 two      145.0
 three    140.0
 dtype: float64,
 a    173.0
 b    149.0
 c     90.0
 d    108.0
 dtype: float64)

In [132]:
df.sum(axis='columns'), df.sum(axis='rows')

(a    173.0
 b    149.0
 c     90.0
 d    108.0
 dtype: float64,
 one      235.0
 two      145.0
 three    140.0
 dtype: float64)

In [133]:
s =  np.arange(10,40,step=3)
x = pd.Series(s)

div, rem = divmod(x,2)
div, rem 

(0     5
 1     6
 2     8
 3     9
 4    11
 5    12
 6    14
 7    15
 8    17
 9    18
 dtype: int32,
 0    0
 1    1
 2    0
 3    1
 4    0
 5    1
 6    0
 7    1
 8    0
 9    1
 dtype: int32)

In [134]:
div, rem = divmod(x,[2, 2, 3, 3, 4, 4, 5, 5, 6, 6])
div, rem

(0    5
 1    6
 2    5
 3    6
 4    5
 5    6
 6    5
 7    6
 8    5
 9    6
 dtype: int32,
 0    0
 1    1
 2    1
 3    1
 4    2
 5    1
 6    3
 7    1
 8    4
 9    1
 dtype: int32)

In [135]:
df
df2 = df.copy()
df2["Four"] = 10
df, df2

(    one  two  three
 a  74.0   99    NaN
 b  74.0   23   52.0
 c  87.0    2    1.0
 d   NaN   21   87.0,
     one  two  three  Four
 a  74.0   99    NaN    10
 b  74.0   23   52.0    10
 c  87.0    2    1.0    10
 d   NaN   21   87.0    10)

In [136]:
df2 +  df

Four    one  three  two
a   NaN  148.0    NaN  198
b   NaN  148.0  104.0   46
c   NaN  174.0    2.0    4
d   NaN    NaN  174.0   42

In [137]:
df3 = df.add(df2,fill_value=3)
df3

Four    one  three  two
a  13.0  148.0    NaN  198
b  13.0  148.0  104.0   46
c  13.0  174.0    2.0    4
d  13.0    NaN  174.0   42

In [138]:
df3.gt(df2)

Four    one  three   two
a  True   True  False  True
b  True   True   True  True
c  True   True   True  True
d  True  False   True  True

In [139]:
df3.ne(df2)

Four   one  three   two
a  True  True   True  True
b  True  True   True  True
c  True  True   True  True
d  True  True   True  True

In [140]:
df3

Four    one  three  two
a  13.0  148.0    NaN  198
b  13.0  148.0  104.0   46
c  13.0  174.0    2.0    4
d  13.0    NaN  174.0   42

In [112]:
np.isnan(df3)

Four    one  three    two
a  False  False   True  False
b  False  False  False  False
c  False  False  False  False
d  False   True  False  False

In [113]:
pd.isna(df3)

Four    one  three    two
a  False  False   True  False
b  False  False  False  False
c  False  False  False  False
d  False   True  False  False

In [114]:
df3

Four    one  three  two
a  13.0  180.0    NaN  196
b  13.0   68.0    0.0   92
c  13.0  128.0    8.0  154
d  13.0    NaN  178.0    4

In [120]:
        (df3 > 0).any()

Four     True
one      True
three    True
two      True
dtype: bool

In [121]:
(df3 > 0).all()

Four      True
one      False
three    False
two       True
dtype: bool

In [189]:
df = pd.DataFrame(np.reshape(np.random.randint(10,size=100000),(10000,10)),index=pd.Series(pd.date_range('1/1/2020',periods=len(df),freq='2h')),columns=list('poiuytrewq') )
df

p  o  i  u  y  t  r  e  w  q
2020-01-01 00:00:00  2  3  6  4  8  3  9  5  8  9
2020-01-01 02:00:00  5  6  9  8  4  6  2  3  3  0
2020-01-01 04:00:00  1  6  3  1  9  8  2  8  8  1
2020-01-01 06:00:00  3  0  2  3  7  7  1  8  6  8
2020-01-01 08:00:00  2  8  9  9  5  0  7  6  6  0
...                 .. .. .. .. .. .. .. .. .. ..
2022-04-12 22:00:00  7  4  7  6  6  0  6  6  2  8
2022-04-13 00:00:00  1  1  1  9  9  5  3  3  0  3
2022-04-13 02:00:00  1  2  9  1  7  2  8  1  2  5
2022-04-13 04:00:00  1  8  5  0  1  7  4  9  2  4
2022-04-13 06:00:00  2  4  4  3  1  9  6  8  4  0

[10000 rows x 10 columns]

In [169]:
np.resize(np.random.randint(10,size=100000),(10000,10))

array([[6, 8, 6, ..., 7, 7, 0],
       [9, 9, 5, ..., 0, 7, 2],
       [3, 5, 7, ..., 4, 8, 5],
       ...,
       [4, 4, 2, ..., 8, 9, 1],
       [5, 0, 0, ..., 7, 5, 4],
       [0, 4, 3, ..., 4, 1, 2]])

In [213]:
df = pd.DataFrame(pd.Series(np.random.randn(10)))

In [214]:
df.min(), df.max(), df.mean(),df.median(), df.count(), df.sum(), df.std(), df.prod(), df.var()

(0   -2.210002
 dtype: float64,
 0    0.999811
 dtype: float64,
 0   -0.722889
 dtype: float64,
 0   -0.784351
 dtype: float64,
 0    10
 dtype: int64,
 0   -7.228889
 dtype: float64,
 0    0.953419
 dtype: float64,
 0    0.019917
 dtype: float64,
 0    0.909008
 dtype: float64)

In [215]:
df.describe(), df.info

(               0
 count  10.000000
 mean   -0.722889
 std     0.953419
 min    -2.210002
 25%    -1.438529
 50%    -0.784351
 75%    -0.163877
 max     0.999811,
 <bound method DataFrame.info of           0
 0  0.999811
 1 -0.923529
 2 -2.210002
 3 -1.266599
 4 -1.523305
 5 -0.187463
 6 -0.645174
 7  0.179227
 8 -0.156016
 9 -1.495839>)

In [218]:
df.describe(include=['number'])

0
count  10.000000
mean   -0.722889
std     0.953419
min    -2.210002
25%    -1.438529
50%    -0.784351
75%    -0.163877
max     0.999811

In [223]:
data = np.random.randint(10,20,size=50)
s = pd.Series(data)
s.value_count()

AttributeError: 'Series' object has no attribute 'value_count'