In [1]:
import numpy as np

In [11]:
a = np.array([1,2,3]),
b= np.array([[1,2,3],[4,5,6]])
a, b

((array([1, 2, 3]),),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [15]:
c = np.array([1,2,3,4,5], ndmin=2)
print (c)



[[1 2 3 4 5]]


In [20]:
d = np.array([1,2,3], dtype=complex),
d

(array([1.+0.j, 2.+0.j, 3.+0.j]),)

In [22]:
e = np.array([1,2,3], dtype=bool)
e

array([ True,  True,  True])

In [27]:
dt = np.dtype(np.int32)
print(dt)
dt = np.dtype('i4')
print(dt)

int32
int32


In [29]:
dt = np.dtype([('age',np.int8)])
dt

dtype([('age', 'i1')])

In [32]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30)], dtype=dt)
a

array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

In [40]:
dt =  np.array([[1,2,3],[4,5,6]])
dt, dt.shape, type(dt), dt.dtype

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3),
 numpy.ndarray,
 dtype('int32'))

In [41]:
dt =  np.array([[1,2,3],['4','5','6']])
dt, dt.shape, type(dt), dt.dtype

(array([['1', '2', '3'],
        ['4', '5', '6']], dtype='<U11'),
 (2, 3),
 numpy.ndarray,
 dtype('<U11'))

In [42]:
dt =  np.array([[1,'2',3],['4','5','6']])
dt, dt.shape, type(dt), dt.dtype

(array([['1', '2', '3'],
        ['4', '5', '6']], dtype='<U11'),
 (2, 3),
 numpy.ndarray,
 dtype('<U11'))

In [52]:
print(dt)
dt1 = dt.reshape(3,2)
print(dt1)
dt2 = dt.reshape(1,6)
dt2
dt3 = dt.reshape(6,1)
dt3

[['1' '2' '3']
 ['4' '5' '6']]
[['1' '2']
 ['3' '4']
 ['5' '6']]


array([['1'],
       ['2'],
       ['3'],
       ['4'],
       ['5'],
       ['6']], dtype='<U11')

In [61]:
a = np.arange(10,42,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [63]:
dt = np.array(a)
dt1 = np.reshape(dt,(4,4))
dt1

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [68]:
dt2 = np.reshape(dt1,(2,2,4))
dt2

array([[[10, 12, 14, 16],
        [18, 20, 22, 24]],

       [[26, 28, 30, 32],
        [34, 36, 38, 40]]])

In [73]:
x = np.empty([3,2], dtype=int)
y = np.ones([3,5], dtype=float)
z = np.zeros([3,5], dtype=float)
print(x)
print(y)
print(z)

[[1484067360        400]
 [         0          0]
 [    131074    4456530]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [76]:
x = np.arange(10,99,2,dtype=float)
x

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50., 52., 54., 56., 58., 60.,
       62., 64., 66., 68., 70., 72., 74., 76., 78., 80., 82., 84., 86.,
       88., 90., 92., 94., 96., 98.])

In [83]:
x = np.linspace(1,5)
print(x)
y = np.logspace(1,5)
print(y)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]
[1.00000000e+01 1.20679264e+01 1.45634848e+01 1.75751062e+01
 2.12095089e+01 2.55954792e+01 3.08884360e+01 3.72759372e+01
 4.49843267e+01 5.42867544e+01 6.55128557e+01 7.90604321e+01
 9.54095476e+01 1.15139540e+02 1.38949549e+02 1.67683294e+02
 2.02358965e+02 2.44205309e+02 2.94705170e+02 3.55648031e+02
 4.29193426e+02 5.17947468e+02 6.25055193e+02 7.54312006e+02
 9.10298178e+02 1.09854114e+03 1.32571137e+03 1.59985872e+03
 1.93069773e+0

In [88]:
a = np.arange(10)
a[2], a[2:], a[:5], a[3:6]

(2, array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4]), array([3, 4, 5]))

In [106]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a.shape)
a([[1,2],[1,2]])

(3, 3)


TypeError: 'numpy.ndarray' object is not callable

In [110]:
##Broadcasting

In [115]:
a = np.array([10,20,30,40])
b = np.array([2,4,6,8])
a*b

array([ 20,  80, 180, 320])

In [118]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0]) 
a.shape, b.shape, a, b, a+b

((4, 3),
 (3,),
 array([[ 0.,  0.,  0.],
        [10., 10., 10.],
        [20., 20., 20.],
        [30., 30., 30.]]),
 array([1., 2., 3.]),
 array([[ 1.,  2.,  3.],
        [11., 12., 13.],
        [21., 22., 23.],
        [31., 32., 33.]]))

In [151]:
a= np.arange(10,100)
a.shape,a

((90,),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
        61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
        78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
        95, 96, 97, 98, 99]))

In [147]:
b=np.reshape(a,(9,10))
b

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [144]:
b.flatten(), b.flat

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
        61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
        78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
        95, 96, 97, 98, 99]),
 <numpy.flatiter at 0x1905a6e3650>)

In [145]:
b.ravel()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [148]:
np.rollaxis(b,axis=0)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [149]:
np.swapaxes(b,0,1)

array([[10, 20, 30, 40, 50, 60, 70, 80, 90],
       [11, 21, 31, 41, 51, 61, 71, 81, 91],
       [12, 22, 32, 42, 52, 62, 72, 82, 92],
       [13, 23, 33, 43, 53, 63, 73, 83, 93],
       [14, 24, 34, 44, 54, 64, 74, 84, 94],
       [15, 25, 35, 45, 55, 65, 75, 85, 95],
       [16, 26, 36, 46, 56, 66, 76, 86, 96],
       [17, 27, 37, 47, 57, 67, 77, 87, 97],
       [18, 28, 38, 48, 58, 68, 78, 88, 98],
       [19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [150]:
b.T

array([[10, 20, 30, 40, 50, 60, 70, 80, 90],
       [11, 21, 31, 41, 51, 61, 71, 81, 91],
       [12, 22, 32, 42, 52, 62, 72, 82, 92],
       [13, 23, 33, 43, 53, 63, 73, 83, 93],
       [14, 24, 34, 44, 54, 64, 74, 84, 94],
       [15, 25, 35, 45, 55, 65, 75, 85, 95],
       [16, 26, 36, 46, 56, 66, 76, 86, 96],
       [17, 27, 37, 47, 57, 67, 77, 87, 97],
       [18, 28, 38, 48, 58, 68, 78, 88, 98],
       [19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [157]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [161]:
np.split(a,axis=0,indices_or_sections=5)

[array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27]),
 array([28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
        45]),
 array([46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
        63]),
 array([64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
        81]),
 array([82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99])]

In [164]:
np.hsplit(a,indices_or_sections=10)

[array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
 array([19, 20, 21, 22, 23, 24, 25, 26, 27]),
 array([28, 29, 30, 31, 32, 33, 34, 35, 36]),
 array([37, 38, 39, 40, 41, 42, 43, 44, 45]),
 array([46, 47, 48, 49, 50, 51, 52, 53, 54]),
 array([55, 56, 57, 58, 59, 60, 61, 62, 63]),
 array([64, 65, 66, 67, 68, 69, 70, 71, 72]),
 array([73, 74, 75, 76, 77, 78, 79, 80, 81]),
 array([82, 83, 84, 85, 86, 87, 88, 89, 90]),
 array([91, 92, 93, 94, 95, 96, 97, 98, 99])]

In [177]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
print(a)
np.vsplit(a,indices_or_sections=2)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


[array([[ 0.,  0.,  0.],
        [10., 10., 10.]]),
 array([[20., 20., 20.],
        [30., 30., 30.]])]

In [1]:
import numpy as np 
x = np.array([[1], [2], [3]]) 
y = np.array([4, 5, 6])  

In [5]:
x.shape, y.shape

((3, 1), (3,))

In [12]:
b =  np.broadcast(x,y)
print(b),b.shape,type(b)
r, c = b.iters

In [15]:
r

In [23]:
x = np.arange(0,30,2).reshape(1,5,3)
print(x)
y = np.squeeze(x)
y

[[[ 0  2  4]
  [ 6  8 10]
  [12 14 16]
  [18 20 22]
  [24 26 28]]]


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [25]:
x.shape,y.shape

((1, 5, 3), (5, 3))

In [33]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
data = np.hstack((x,y))
data1 = np.vstack((x,y))
x,y,data, data1

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]))

In [47]:
x = np.arange(0,30,2)
y = np.split(x,[3,5])
y

[array([0, 2, 4]),
 array([6, 8]),
 array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])]

In [50]:
np.reshape(x,(3,5))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [76]:
x = np.arange(9).reshape(3,3)
y = np.arange(12,15,1).reshape(1,3)
x,y,np.append(x,y,axis=0),np.append(x,y)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[12, 13, 14]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [12, 13, 14]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 12, 13, 14]))

In [77]:
np.unique(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
np.delete(x,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [83]:
np.insert(x,0,111)

array([111,   0,   1,   2,   3,   4,   5,   6,   7,   8])

In [88]:
p = np.array([2,3,5])
print(np.power(x,3))
print(np.power(x,p))


[[  0   1   8]
 [ 27  64 125]
 [216 343 512]]
[[    0     1    32]
 [    9    64  3125]
 [   36   343 32768]]


In [93]:
x = np.random.randn(20)
x, np.average(x), np.mean(x), np.median(x)

(array([-0.8901398 ,  1.63004534,  0.61898221, -0.378137  , -0.31973693,
        -0.48882266,  0.02876739,  0.79083579,  0.27418882, -1.04128189,
         1.72276617,  0.83276633, -0.49140702,  0.37461419,  0.32636967,
         0.32002308,  1.30243502,  0.02350321, -0.15065722, -0.16315314]),
 0.21609807843928225,
 0.21609807843928225,
 0.15147810497303574)

In [95]:
np.min(x),np.max(x),np.amin(x),np.amax(x)

(-1.0412818878777734, 1.7227661742146, -1.0412818878777734, 1.7227661742146)

In [108]:
np.random.seed(0)
x = np.random.randint(0,100,25)
x, np.sort(x,kind="quicksort")

(array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
        87, 46, 88, 81, 37, 25, 77, 72]),
 array([ 9, 12, 21, 25, 36, 37, 39, 44, 46, 47, 58, 64, 65, 67, 67, 70, 72,
        77, 81, 83, 87, 87, 88, 88, 88]))

In [126]:
a = np.array([[10,10], [2,3], [4,5]])
b = a
a,b

(array([[10, 10],
        [ 2,  3],
        [ 4,  5]]),
 array([[10, 10],
        [ 2,  3],
        [ 4,  5]]))

In [119]:
a[0,0]=100
b

array([[100,  10],
       [  2,   3],
       [  4,   5]])

In [127]:
c = a.copy()
c

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [128]:
a[0,0] = 89
c

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])