In [135]:
What_Were_Covering = [
"0. An end to end scikit workflow",
"1. Import the data and clean the data i,e getting data ready",
"2. Choose the right algorithom / estimator for the problem statement",
"3. Fit the model/algorithm and predict the values",
"4. Evaluating the model",
"5. Improve the model",
"6. Save and load the model",
"7. Putting it all togher"]
What_Were_Covering

['0. An end to end scikit workflow',
 '1. Import the data and clean the data i,e getting data ready',
 '2. Choose the right algorithom / estimator for the problem statement',
 '3. Fit the model/algorithm and predict the values',
 '4. Evaluating the model',
 '5. Improve the model',
 '6. Save and load the model',
 '7. Putting it all togher']

# 1. Get the data ready

In [136]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
heart_disease = pd.read_csv("C:\Jayaprakash\DataScience\Projects\Test Data\heart-disease.csv")
heart_disease.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [137]:
#Create the list of features (X-Axis)
X = heart_disease.drop("target",axis=1)

#create the labels (Y-Axis)
y = heart_disease["target"]

# 2. Choose the right model and hyperparameters

In [138]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()
#clf.get_params() n_estimators=100

# 3. Fit the model to the training data

In [139]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test  = train_test_split(X,y, test_size = 0.2)
clf.fit(X_train,y_train)
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
77    59    1   1       140   221    0        1      164      1      0.0   
19    69    0   3       140   239    0        1      151      0      1.8   
289   55    0   0       128   205    0        2      130      1      2.0   
260   66    0   0       178   228    1        1      165      1      1.0   
134   41    0   1       126   306    0        1      163      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
294   44    1   0       120   169    0        1      144      1      2.8   
11    48    0   2       130   275    0        1      139      0      0.2   
76    51    1   2       125   245    1        0      166      0      2.4   
205   52    1   0       128   255    0        1      161      1      0.0   
257   50    1   0       144   200    0        0      126      1      0.9   

     slope  ca  thal  
77       2   0     2  
19       2   2     2  
289      1   1     3  
260      1   2     3  
134      2   0     2  
..     ...  ..   ...  
294      0   0     1  
11       2   0     2  
76       1   0     2  
205      2   1     3  
257      1   0     3  

[242 rows x 13 columns]

In [140]:
y_preds = clf.predict(X_test)
y_preds

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

# 4. Evaluate the model on the training data and test data

In [141]:
#Evaluating the model on the train data set and it will return 1.0 because it is testing against itself.
clf.score(X_train,y_train)

1.0

In [142]:
#clf is now a model which is trained. Now we are passing the test data X,y and tesing it for accuracy. 
# The result will tell how accurecy is our model
clf.score(X_test,y_test)

0.9344262295081968

In [143]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [144]:
print (classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.85      0.94      0.89        18
           1       0.98      0.93      0.95        43

    accuracy                           0.93        61
   macro avg       0.91      0.94      0.92        61
weighted avg       0.94      0.93      0.94        61



In [145]:
cm = confusion_matrix(y_test,y_preds)
cm

array([[17,  1],
       [ 3, 40]], dtype=int64)

In [146]:
accuracy_score(y_test,y_preds)

0.9344262295081968

In [147]:
#This will loop from 10 to 100 for 10 instance and will assign to n_estimators and find the score 10 times.
np.random.seed(42)
for i in range(10,100,10):
    #print(f"Trying model with {i} estimator ....")
    model = RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print(f"Model accuracy for n_estimater {i} is : {model.score(X_test,y_test)*100}")
    

Model accuracy for n_estimater 10 is : 81.9672131147541
Model accuracy for n_estimater 20 is : 88.52459016393442
Model accuracy for n_estimater 30 is : 86.88524590163934
Model accuracy for n_estimater 40 is : 90.1639344262295
Model accuracy for n_estimater 50 is : 90.1639344262295
Model accuracy for n_estimater 60 is : 88.52459016393442
Model accuracy for n_estimater 70 is : 90.1639344262295
Model accuracy for n_estimater 80 is : 91.80327868852459
Model accuracy for n_estimater 90 is : 91.80327868852459


In [148]:
from sklearn.model_selection import cross_val_score

In [149]:
#This is an example for cross_val_score, it returns results based on the cv value. if it is 4 , it will return 4 score, 
# we can compare or take mean of these values 
np.random.seed(42)

cv = cross_val_score(clf,X,y,cv=4)
cv, cv.mean()

(array([0.82894737, 0.88157895, 0.76315789, 0.76      ]), 0.8084210526315789)

In [150]:
#it is combinging both score and cross validation and we can judge which is better
for i in range(10,100,10):
    model = RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print(f"Model accuracy of n_estimators {i} with score is {model.score(X_test,y_test)*100 } % ")
    print(f"Model accuracy of n_estimators {i} with cross_validation is {np.mean(cross_val_score(model,X,y,cv=5))} %")

Model accuracy of n_estimators 10 with score is 81.9672131147541 % 
Model accuracy of n_estimators 10 with cross_validation is 0.8085792349726775 %
Model accuracy of n_estimators 20 with score is 90.1639344262295 % 
Model accuracy of n_estimators 20 with cross_validation is 0.8020218579234972 %
Model accuracy of n_estimators 30 with score is 85.24590163934425 % 
Model accuracy of n_estimators 30 with cross_validation is 0.7950819672131147 %
Model accuracy of n_estimators 40 with score is 85.24590163934425 % 
Model accuracy of n_estimators 40 with cross_validation is 0.8083060109289617 %
Model accuracy of n_estimators 50 with score is 88.52459016393442 % 
Model accuracy of n_estimators 50 with cross_validation is 0.8115846994535518 %
Model accuracy of n_estimators 60 with score is 83.60655737704919 % 
Model accuracy of n_estimators 60 with cross_validation is 0.8182513661202186 %
Model accuracy of n_estimators 70 with score is 93.44262295081968 % 
Model accuracy of n_estimators 70 with 

In [151]:
np.random.seed(42)

from sklearn.model_selection import GridSearchCV

param_grid = {'n_estimators': [ i for i in range(10,100,10) ]}

grid =  GridSearchCV(RandomForestClassifier(),param_grid,cv=5)

grid.fit(X,y)
grid.best_params_

{'n_estimators': 80}